### PR TITLE
sd: update sdmmc_wait_ready to support SPI mode utilization

### PR DESCRIPTION
**Pull request by ghost**
Please note, that this is not even merged in upstream zephyr. See the discussion of it here: https://github.com/zephyrproject-rtos/zephyr/issues/52931

Update sdmmc_wait_ready to support SPI mode, where host controller is not aware if SD card is busy. This will allow cards that do not return to ready to be polled for busy status until the SD data timeout expires

Signed-off-by: Daniel DeGrasse <daniel.degrasse@nxp.com>

### CODE REVIEW

**Comment by AndreyDodonov-EH** [comment]
@clamattia Looks good, but I think the fix consists of two parts, or?
Also this one https://github.com/nxp-zephyr/zephyr/commit/2c2b8c342247ff767ee369169a74dbcf09b5edc6 ?

**Comment by ghost** [comment]
> @clamattia Looks good, but I think the fix consists of two parts, or? Also this one [nxp-zephyr/zephyr@2c2b8c3](https://github.com/nxp-zephyr/zephyr/commit/2c2b8c342247ff767ee369169a74dbcf09b5edc6) ?

I have realized, that these were already added by @maluJ  earlier: https://github.com/endresshauser-lp/sdk-zephyr/commit/5fce7cef5e1d8e49fa8f6383867399954f89c9e9 . I chose not to revert  and cherry-pick https://github.com/nxp-zephyr/zephyr/commit/2c2b8c342247ff767ee369169a74dbcf09b5edc6 to avoid breaking branches that currently point to the head of https://github.com/endresshauser-lp/sdk-zephyr/tree/v3.1.99-ncs1-qwx43-changes.

**Review by AndreyDodonov-EH — APPROVED** [review]
Looks good to me!
Just make sure to reference resulting merge commit hash in west.yml in our main repo

**Comment by ghost** [comment]
> Looks good to me! Just make sure to reference resulting merge commit hash in west.yml in our main repo

Good point :+1: see https://github.com/endresshauser-lp/iiot-qwx43-firmware-nrf9160/pull/309

**Pull request merged**
